### ISSUE TITLE
大家知道多线程是为了提高程序的并发，同样多协程也是一样的为了提高并发 语句读起来变扭

### ISSUE THREAD

**Issue by wuqinqiang** [swoole-plus/report#11]
原文地址:https://wiki.swoole.com/#/coroutine?id=%e5%8d%8f%e7%a8%8b%e8%b0%83%e5%ba%a6

实际内容:同样多协程也是一样的为了提高并发 

期望内容:多协程也同样是为了提高并发

**Comment by sy-records** [comment]
这里有些口语化，已经修改，谢谢。
