### ISSUE TITLE
疑问: 一键协程化中 gethookflags 无法调用

### ISSUE THREAD

**Issue by sdfjklmin** [swoole-plus/report#12]
文档链接: https://wiki.swoole.com/#/runtime?id=gethookflags
情况说明: 无法调用 `Swoole\Runtime::getHookFlags()`,` Call to undefined method Swoole\Runtime::getHookFlags()`
具体信息: 
*  版本信息 => swoole version (4.4.8),php version(7.3.10)
*  配置信息 => swoole配置全为enabled,Directive为On
*  虽然 `swoole-ide-helper`能够调用,但 `get_class_methods('\Swoole\Runtime')`只有`enableStrictMode,enableCoroutine`

**Comment by sy-records** [comment]
该API在[v4.4.12](https://github.com/swoole/swoole-src/releases/tag/v4.4.12)版本中加入的。
