### ISSUE TITLE
Timer示例中参数错误

### ISSUE THREAD

**Issue by sdfjklmin** [swoole-plus/report#16]
文档链接: https://wiki.swoole.com/#/timer?id=tick
实际内容: 使用示例 -> 正确示例,Swoole\Timer::tick 的 ...$params 参数错误
期望内容: 
```
Swoole\Timer::tick(3000, function (int $timer_id, $paramA, $paramB) {

}, 'paramA', 'paramB');

**Comment by sdfjklmin** [comment]
有个小问题,这里如果传入未定义的变量 `$paramA,$paramB`,会报 4次 `Undefined variable`,按理来说应该是两次
![timer](https://user-images.githubusercontent.com/13510734/76934810-d0bfe000-692a-11ea-81b9-ce59705bf180.png)

**Comment by sy-records** [comment]
刚才修改过了。
```php
Swoole\Timer::tick(3000, function (int $timer_id, $param1, $param2) {
    echo "timer_id #$timer_id, after 3000ms.\n";
    echo "param1 is $param1, param2 is $param2.\n";

    Swoole\Timer::tick(14000, function ($timer_id) {
        echo "timer_id #$timer_id, after 14000ms.\n";
    });
}, "A", "B");
```

**Comment by sy-records** [comment]
> 有个小问题,这里如果传入未定义的变量 `$paramA,$paramB`,会报 4次 `Undefined variable`,按理来说应该是两次
> ![timer](https://user-images.githubusercontent.com/13510734/76934810-d0bfe000-692a-11ea-81b9-ce59705bf180.png)

这个是php配置问题，修改`php.ini`中的`display_errors = Off`

**Comment by sdfjklmin** [comment]
thanks
