### ISSUE TITLE
scheduler页的一个跳转路径错误

### ISSUE THREAD

**Issue by linvsCode** [swoole-plus/report#22]
截图位置：![image](https://user-images.githubusercontent.com/20921898/77495247-f5fca300-6e82-11ea-8d38-c3f98003bd46.png)
文档路径：[Coroutine\Scheduler](https://wiki.swoole.com/#/coroutine/scheduler)的`EventLoop `跳转路径
实际内容：https://wiki.swoole.com/#/user?id=%e4%bb%80%e4%b9%88%e6%98%afeventloop
期望内容：https://wiki.swoole.com/#/learn?id=%e4%bb%80%e4%b9%88%e6%98%afeventloop

**Comment by sy-records** [comment]
Thanks，已添加至文档贡献者列表。
