### ISSUE TITLE
其它建议

### ISSUE THREAD

**Issue by sdfjklmin** [swoole-plus/report#4]
文档链接: https://wiki.swoole.com/#/server/setting?id=dispatch_func
步骤信息: 编写 PHP 函数
实际内容: 
`
    $server->set(array(
        'dispatch_func' => function ($server, $fd, $type, $data) {
            var_dump($fd, $type, $data);
            return intval($data[0]);
        },
    ));
`
具体说明: 
    这里的 `$data` 始终以 `string` 类型接收,最后 return 时,console 台会报 Notice

**Comment by sy-records** [comment]
这个参数的作用是当swoole内置的6种 [dispatch_mode](https://wiki.swoole.com/#/server/setting?id=dispatch_func) 无法满足需求的时候，用户自定义`function`来实现`dispatch`的逻辑；

示例中返回的是0，没什么问题；

自定义方法中必须返回一个 0 到 worker_num 的数字，表示数据包投递的目标工作进程ID，小于 0 或者大于等于 worker_num 为异常目标 ID，dispatch 的数据将会被丢弃。
