### ISSUE TITLE
WebSocketServer 中 websocket_status 说明有歧义 

### ISSUE THREAD

**Issue by sdfjklmin** [swoole-plus/report#5]
* 文档链接: https://wiki.swoole.com/#/websocket_server
* 具体步骤: WebSocketServer -> 如何判断连接是否为 WebSocket 客户端
* 实际内容: 通过使用 $server->connection_info($fd) 获取连接信息，返回的数组中有一项为 websocket_status，根据此状态可以判断是否为 WebSocket 客户端。
* 具体说明
    * 在 `websocket_status 连接状态` 说明中, 3 只表示了 `已握手成功等待浏览器发送数据帧`
    * 实际在事件`open`,`message`,`close`中 websocket_status 均为 3

**Comment by twose** [comment]
我感觉没有什么歧义

**Comment by sdfjklmin** [comment]
好吧 ☺
