### ISSUE TITLE
swoole4文档里process\pool里拼写错误

### ISSUE THREAD

**Issue by baly2000** [swoole-plus/report#7]
- 设置为 SWOOLE_IPC_SOCK 表示使用 Socket 进行通信，需要使用 listen 方法指定监听的地址和端口；
实际运行中设置成SWOOLE_IPC_SOCK会报错
![image](https://user-images.githubusercontent.com/8666581/76186709-2818ce80-620e-11ea-8eae-1ddad4c40dec.png)
改成SWOOLE_IPC_SOCKET就可以正常运行了

**Comment by sy-records** [comment]
Thanks，已添加至贡献者列表。
