### ISSUE TITLE
参数标注不一致

### ISSUE THREAD

**Issue by zhmm** [swoole-plus/report#8]
https://wiki.swoole.com/#/server/methods?id=task
对参数 int $dstWorkerId 说明：
功能：可以指定要给投递给哪个 Task 进程，传入 ID 即可，范围是 0 - (serv->task_worker_num -1)

https://wiki.swoole.com/#/server/methods?id=taskwait
对参数 int $dstWorkerId 说明：
功能：指定要给投递给哪个 Task 进程，传入 ID 即可，范围是 0 - serv->task_worker_num

范围标记不统一

**Comment by sy-records** [comment]
Thanks，已经修正，感谢贡献。已添加至文档贡献者列表
